#!/usr/bin/env node
/**
 * Pulls the client's current website into this project so the prototype is
 * built from their real logo, photography and words.
 *
 *   logo + favicon        → public/brand/
 *   every page's images   → public/images/<page-slug>/01.webp (+ 01-1200.webp)
 *   every page's copy     → scraped/pages/<page-slug>.md  and  scraped/site.json
 *   image manifest        → src/content/media.json   (the site reads this)
 *
 * Usage:
 *   npm run scrape
 *   npm run scrape -- --base https://www.example.co.nz --max-pages 80
 *   npm run scrape -- --no-images        (copy only)
 *
 * Re-running is safe: it overwrites the generated files and nothing else.
 */
import { spawnSync } from "node:child_process"
import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import * as cheerio from "cheerio"
import sharp from "sharp"

// Node's built-in fetch only honours HTTPS_PROXY when NODE_USE_ENV_PROXY is set at
// startup — re-launch once with it so the script also works behind corporate proxies.
if (process.env.HTTPS_PROXY && !process.env.NODE_USE_ENV_PROXY) {
  const result = spawnSync(process.execPath, process.argv.slice(1), {
    stdio: "inherit",
    env: { ...process.env, NODE_USE_ENV_PROXY: "1" },
  })
  process.exit(result.status ?? 1)
}

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const args = parseArgs(process.argv.slice(2))
const BASE = new URL(args.base ?? "https://www.beechtreebuilding.co.nz/")
const MAX_PAGES = Number(args["max-pages"] ?? 80)
const WITH_IMAGES = !args["no-images"]
const MIN_IMAGE_WIDTH = 500
const USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36 BeechtreeSiteMigration/1.0"

const OUT = {
  brand: path.join(ROOT, "public/brand"),
  images: path.join(ROOT, "public/images"),
  scraped: path.join(ROOT, "scraped"),
  manifest: path.join(ROOT, "src/content/media.json"),
}

const SKIP_PATH = /^\/(cart|account|commerce|config|api|search|s\/|static\/|universal\/|checkout)/i
const SKIP_EXT = /\.(pdf|jpe?g|png|gif|webp|svg|zip|mp4|mov|docx?|xlsx?)$/i

main().catch((error) => {
  console.error("\n✖ Scrape failed:", error.message)
  if (/fetch failed|ENOTFOUND|ECONNREFUSED|403/.test(String(error.message) + String(error.cause))) {
    console.error("  Check the site is reachable from this machine (network / proxy / firewall).")
  }
  process.exit(1)
})

async function main() {
  console.log(`→ Crawling ${BASE.origin} (max ${MAX_PAGES} pages)…`)
  const pages = await crawl()
  console.log(`✓ ${pages.length} pages`)

  const manifest = {
    $comment:
      "GENERATED by `npm run scrape` — maps each page of the old site to its downloaded images. Safe to re-generate. Hand-picked overrides belong in src/content/*.ts instead.",
    source: BASE.origin,
    scrapedAt: new Date().toISOString(),
    logo: null,
    favicon: null,
    pages: {},
  }

  if (WITH_IMAGES) {
    await fs.mkdir(OUT.brand, { recursive: true })
    const home = pages.find((p) => p.slug === "home") ?? pages[0]
    if (home?.logoUrl) manifest.logo = await saveLogo(home.logoUrl)
    if (home?.faviconUrl) manifest.favicon = await saveFavicon(home.faviconUrl)
    console.log(manifest.logo ? `✓ Logo → ${manifest.logo}` : "! No logo found — the site will use its text wordmark")

    const downloaded = new Map() // source URL → SiteImage (same photo reused across pages is fetched once)
    for (const page of pages) {
      const images = []
      let index = 0
      for (const candidate of page.images) {
        const key = canonicalImageKey(candidate.url)
        let image
        if (downloaded.has(key)) {
          // Already fetched for another page: copy the files so every page's folder is complete
          image = await copyImage(downloaded.get(key), page.slug, index + 1)
        } else {
          image = await saveImage(candidate, page.slug, index + 1)
          downloaded.set(key, image)
        }
        if (image) {
          images.push({ ...image, alt: candidate.alt || image.alt || "" })
          index++
        }
      }
      manifest.pages[page.slug] = { title: page.title, images }
      console.log(`  ${page.slug.padEnd(28)} ${String(images.length).padStart(3)} images`)
    }
  }

  await writeCopy(pages)
  await fs.writeFile(OUT.manifest, JSON.stringify(manifest, null, 2) + "\n")
  console.log(`\n✓ Manifest → ${path.relative(ROOT, OUT.manifest)}`)
  console.log(`✓ Copy     → ${path.relative(ROOT, OUT.scraped)}/`)
  console.log("\nNext: review scraped/pages/*.md and merge any wording into src/content/.")
}

/* ─────────────────────────────── Crawl ─────────────────────────────── */

async function crawl() {
  const queue = [normalise(BASE)]
  const seen = new Set(queue)
  const pages = []

  while (queue.length && pages.length < MAX_PAGES) {
    const url = queue.shift()
    let html
    try {
      const res = await fetchWithRetry(url)
      if (!res.ok || !(res.headers.get("content-type") ?? "").includes("text/html")) continue
      html = await res.text()
    } catch (error) {
      console.warn(`  ! ${url}: ${error.message}`)
      continue
    }

    const page = parsePage(url, html)
    pages.push(page)
    process.stdout.write(`  · ${page.slug}\n`)

    for (const link of page.links) {
      if (!seen.has(link)) {
        seen.add(link)
        queue.push(link)
      }
    }
    await sleep(200) // be polite
  }
  return pages
}

function parsePage(url, html) {
  // scriptingEnabled:false makes <noscript> contents parse as real elements —
  // Squarespace puts the full-resolution <img> tags inside them.
  const $ = cheerio.load(html, { scriptingEnabled: false })
  const pageUrl = new URL(url)
  const slug = slugFor(pageUrl)

  const title = ($("title").first().text() || "")
    .replace(/\s+[—–|-]\s+.*$/, "")
    .trim()
  const description = $('meta[name="description"]').attr("content")?.trim() ?? ""

  // Links (same site only)
  const links = new Set()
  $("a[href]").each((_, el) => {
    const href = $(el).attr("href")
    if (!href || /^(mailto|tel|javascript):/i.test(href)) return
    try {
      const next = new URL(href, pageUrl)
      if (sameSite(next) && !SKIP_PATH.test(next.pathname) && !SKIP_EXT.test(next.pathname)) {
        links.add(normalise(next))
      }
    } catch {
      /* ignore malformed hrefs */
    }
  })

  // Logo & favicon
  const logoEl = $(
    [
      ".header-title-logo img",
      ".site-branding img",
      'header [class*="logo"] img',
      '[class*="logo"] img',
      'img[alt*="logo" i]',
      "header img",
    ].join(", "),
  ).first()
  const logoUrl = resolveImageUrl(bestSource($, logoEl), pageUrl)
  const faviconUrl = resolveImageUrl(
    $('link[rel="apple-touch-icon"]').attr("href") ?? $('link[rel~="icon"]').attr("href"),
    pageUrl,
  )

  // Page images, in document order, excluding site chrome
  const images = []
  const seenImages = new Set()
  const pushImage = (raw, alt = "") => {
    const resolved = resolveImageUrl(raw, pageUrl)
    if (!resolved || /\.(svg|gif)(\?|$)/i.test(resolved)) return
    const key = canonicalImageKey(resolved)
    if (seenImages.has(key) || (logoUrl && key === canonicalImageKey(logoUrl))) return
    seenImages.add(key)
    images.push({ url: resolved, alt: alt.trim() })
  }

  const content = $("main, #page, #content, .content-wrapper, article").first()
  const scope = content.length ? content : $("body")
  scope.find("[data-image], img, [style*='background-image']").each((_, el) => {
    const $el = $(el)
    if ($el.closest("header, footer, nav").length) return
    if (el.tagName === "img") pushImage(bestSource($, $el), $el.attr("alt") ?? "")
    else if ($el.attr("data-image")) pushImage($el.attr("data-image"), $el.attr("data-image-alt") ?? "")
    else {
      const bg = /url\((['"]?)(.*?)\1\)/.exec($el.attr("style") ?? "")?.[2]
      if (bg) pushImage(bg)
    }
  })
  const ogImage = $('meta[property="og:image"]').attr("content")
  if (ogImage) pushImage(ogImage, title)

  // Copy, as lightweight markdown blocks in reading order
  const copyScope = scope.clone()
  copyScope.find("script, style, noscript, nav, header, footer, form, svg, button").remove()
  const blocks = []
  copyScope.find("h1, h2, h3, h4, p, li, blockquote").each((_, el) => {
    const $el = $(el)
    if ($el.parents("li, blockquote").length && el.tagName === "p") return
    const text = $el.text().replace(/\s+/g, " ").trim()
    if (!text || text.length < 2 || blocks.at(-1)?.text === text) return
    blocks.push({ type: el.tagName, text })
  })

  return { url, slug, title, description, links: [...links], logoUrl, faviconUrl, images, blocks }
}

/* ─────────────────────────────── Images ─────────────────────────────── */

async function saveImage(candidate, slug, n) {
  try {
    const buffer = await download(largestVariant(candidate.url))
    const meta = await sharp(buffer).metadata()
    if (!meta.width || meta.width < MIN_IMAGE_WIDTH) return null // icons, spacers, tiny thumbs

    const dir = path.join(OUT.images, slug)
    await fs.mkdir(dir, { recursive: true })
    const name = String(n).padStart(2, "0")
    const pipeline = sharp(buffer).rotate() // respect EXIF orientation

    const large = await pipeline
      .clone()
      .resize({ width: 2400, withoutEnlargement: true })
      .webp({ quality: 80 })
      .toFile(path.join(dir, `${name}.webp`))
    await pipeline
      .clone()
      .resize({ width: 1200, withoutEnlargement: true })
      .webp({ quality: 78 })
      .toFile(path.join(dir, `${name}-1200.webp`))

    return {
      src: `/images/${slug}/${name}.webp`,
      srcSmall: `/images/${slug}/${name}-1200.webp`,
      width: large.width,
      height: large.height,
      alt: candidate.alt,
    }
  } catch (error) {
    console.warn(`  ! image ${candidate.url}: ${error.message}`)
    return null
  }
}

async function copyImage(image, slug, n) {
  if (!image) return null
  const dir = path.join(OUT.images, slug)
  await fs.mkdir(dir, { recursive: true })
  const name = String(n).padStart(2, "0")
  const from = (src) => path.join(ROOT, "public", src)
  await fs.copyFile(from(image.src), path.join(dir, `${name}.webp`))
  await fs.copyFile(from(image.srcSmall), path.join(dir, `${name}-1200.webp`))
  return { ...image, src: `/images/${slug}/${name}.webp`, srcSmall: `/images/${slug}/${name}-1200.webp` }
}

async function saveLogo(url) {
  try {
    const buffer = await download(largestVariant(url))
    if (/\.svg(\?|$)/i.test(url) || buffer.subarray(0, 200).toString().includes("<svg")) {
      await fs.writeFile(path.join(OUT.brand, "logo.svg"), buffer)
      return "/brand/logo.svg"
    }
    // Trim surrounding whitespace so the logo sits tight in the header
    await sharp(buffer).trim().png().toFile(path.join(OUT.brand, "logo.png"))
    return "/brand/logo.png"
  } catch (error) {
    console.warn(`  ! logo ${url}: ${error.message}`)
    return null
  }
}

async function saveFavicon(url) {
  try {
    const buffer = await download(url)
    if (/\.ico(\?|$)/i.test(url)) {
      await fs.writeFile(path.join(OUT.brand, "favicon.ico"), buffer)
      return "/brand/favicon.ico"
    }
    await sharp(buffer).resize(180, 180, { fit: "contain", background: "#00000000" }).png().toFile(path.join(OUT.brand, "favicon.png"))
    return "/brand/favicon.png"
  } catch (error) {
    console.warn(`  ! favicon ${url}: ${error.message}`)
    return null
  }
}

/** Squarespace serves any size via ?format=NNNNw — always ask for the biggest. */
function largestVariant(url) {
  const u = new URL(url)
  if (/squarespace-cdn\.com|sqspcdn\.com/.test(u.hostname)) u.searchParams.set("format", "2500w")
  return u.toString()
}

function bestSource($, $el) {
  if (!$el?.length) return undefined
  const srcset = $el.attr("data-srcset") ?? $el.attr("srcset")
  if (srcset) {
    const largest = srcset
      .split(",")
      .map((part) => part.trim().split(/\s+/))
      .map(([u, w]) => ({ u, w: parseInt(w, 10) || 0 }))
      .sort((a, b) => b.w - a.w)[0]?.u
    if (largest) return largest
  }
  return $el.attr("data-src") ?? $el.attr("data-image") ?? $el.attr("src")
}

function resolveImageUrl(raw, base) {
  if (!raw || raw.startsWith("data:")) return undefined
  try {
    return new URL(raw.trim(), base).toString()
  } catch {
    return undefined
  }
}

function canonicalImageKey(url) {
  const u = new URL(url)
  return `${u.hostname}${u.pathname}`.toLowerCase()
}

/* ─────────────────────────────── Copy ─────────────────────────────── */

async function writeCopy(pages) {
  const dir = path.join(OUT.scraped, "pages")
  await fs.mkdir(dir, { recursive: true })
  for (const page of pages) {
    const lines = [`<!-- ${page.url} -->`, `# ${page.title || page.slug}`, ""]
    if (page.description) lines.push(`> ${page.description}`, "")
    for (const block of page.blocks) {
      if (/^h[1-4]$/.test(block.type)) lines.push(`${"#".repeat(Number(block.type[1]) + 1)} ${block.text}`, "")
      else if (block.type === "li") lines.push(`- ${block.text}`)
      else if (block.type === "blockquote") lines.push(`> ${block.text}`, "")
      else lines.push(block.text, "")
    }
    await fs.writeFile(path.join(dir, `${page.slug}.md`), lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n")
  }
  const summary = pages.map(({ url, slug, title, description, blocks, images }) => ({
    url,
    slug,
    title,
    description,
    blocks,
    sourceImages: images.map((i) => i.url),
  }))
  await fs.writeFile(path.join(OUT.scraped, "site.json"), JSON.stringify(summary, null, 2) + "\n")
}

/* ─────────────────────────────── Utils ─────────────────────────────── */

async function fetchWithRetry(url, attempts = 3) {
  for (let i = 1; ; i++) {
    try {
      return await fetch(url, {
        headers: { "user-agent": USER_AGENT, accept: "text/html,image/*,*/*" },
        redirect: "follow",
        signal: AbortSignal.timeout(30_000),
      })
    } catch (error) {
      if (i >= attempts) throw error
      await sleep(1000 * 2 ** i)
    }
  }
}

async function download(url) {
  const res = await fetchWithRetry(url)
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

function sameSite(url) {
  const bare = (h) => h.replace(/^www\./, "")
  return /^https?:$/.test(url.protocol) && bare(url.hostname) === bare(BASE.hostname)
}

function normalise(url) {
  const u = new URL(url)
  u.hash = ""
  u.search = ""
  u.hostname = BASE.hostname
  u.protocol = BASE.protocol
  u.port = BASE.port
  if (u.pathname.length > 1) u.pathname = u.pathname.replace(/\/+$/, "")
  return u.toString()
}

function slugFor(url) {
  const slug = url.pathname
    .replace(/^\/+|\/+$/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9/-]+/g, "-")
    .replace(/\//g, "--")
  return slug || "home"
}

function parseArgs(argv) {
  const out = {}
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (!arg.startsWith("--")) continue
    const [key, inline] = arg.slice(2).split("=")
    if (inline !== undefined) out[key] = inline
    else if (argv[i + 1] && !argv[i + 1].startsWith("--")) out[key] = argv[++i]
    else out[key] = true
  }
  return out
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}
